# netlify.toml
[build]
  publish = "public"   # or "build", "dist", etc.

[[redirects]]
  from   = "/:student"
  to     = "/index.html"
  status = 200

[[redirects]]
  from   = "/:student/*"
  to     = "/index.html"
  status = 200
